const pt = {
  title: 'Decisões da abelha', description: 'Estas solicitações pertencem às tarefas indicadas. Suas escolhas ficam registradas mesmo se você fechar esta página.',
  empty: 'Nenhuma decisão registrada ainda.', loading: 'Carregando decisões…', refresh: 'Atualizar decisões', more: 'Carregar mais decisões',
  monitorFailure: 'Não foi possível atualizar as decisões. Atualize antes de decidir; os dados podem estar desatualizados.',
  uncertain: 'A decisão pode ter sido registrada. Confira o estado atualizado antes de repetir. Nenhuma decisão é reenviada automaticamente.',
  pending: 'Aguardando sua decisão', approved: 'Consentimento registrado', denied: 'Decisão registrada · geração não liberada', revoked: 'Consentimento revogado', consumed: 'Consentimento utilizado no início da chamada',
  stale: 'Esta solicitação não corresponde mais ao estado atual. Atualize a tarefa e as decisões.', expired: 'Esta solicitação expirou. Retome a tarefa para solicitar uma nova decisão.',
  task: 'Tarefa', objective: 'Objetivo', expectedResult: 'Resultado esperado', reviewTask: 'Revisar objetivo e resultado esperado', model: 'Modelo', destination: 'Destino', environment: 'Ambiente', identity: 'Identidade', action: 'Ação', control_plane: 'Serviço Bees', bees_user: 'Seu acesso no Bees', generate: 'Gerar uma resposta de texto',
  scope: 'Escopo da regra', exactScope: 'Somente esta abelha, ação, destino, modelo, ambiente e identidade. A regra vale também para pedidos futuros neste escopo.',
  onceScope: 'Somente esta chamada preparada. Mudar instruções, contexto, modelo, regras ou destino invalida o consentimento.',
  expiration: 'Solicitação válida até {{time}}', cost: 'O conteúdo da tarefa e seu contexto serão enviados ao destino indicado. A chamada pode consumir créditos do provedor.',
  allow_once: 'Permitir uma vez', allow_rule: 'Salvar regra neste escopo', ask: 'Sempre perguntar', deny: 'Bloquear neste escopo',
  help_allow_once: 'Autoriza esta chamada uma vez e coloca a tarefa na fila. Dispensa a pergunta somente para esta chamada; bloqueios continuam prevalecendo. Não cria uma regra permanente.',
  help_allow_rule: 'Salva uma permissão para o escopo mostrado e coloca a tarefa na fila. Bloqueios aplicáveis continuam prevalecendo.',
  help_ask: 'Salva uma regra para perguntar neste escopo. Esta decisão não libera nem retoma a tarefa.',
  help_deny: 'Salva um bloqueio neste escopo. A tarefa permanece parada.',
  confirm: 'Confirmar decisão', saving: 'Registrando…', back: 'Voltar', reason: 'Motivo (opcional)', decisionSaved: 'Decisão registrada. O serviço reavalia as regras antes da chamada.',
  revoke: 'Revogar consentimento', revokeImpact: 'Revoga somente o consentimento pontual ainda não utilizado. Uma chamada já iniciada não é desfeita. Regras permanentes são editadas em Autonomia.',
  confirmRevoke: 'Confirmar revogação', revokedSaved: 'Consentimento revogado.', editPolicies: 'Editar regras na conversa', policiesHelp: 'Digite /autonomia ou use o botão para abrir o editor de regras. Texto do modelo não altera permissões.', closePolicies: 'Fechar editor de regras',
  reviewFirst: 'Escolha o alcance e confirme abaixo.',
  lastDecision: 'Última decisão', stillWaiting: 'a tarefa continua aguardando',
}
type Translations = Record<keyof typeof pt, string>
const en: Translations = {
  title: 'Bee decisions', description: 'These requests belong to the named tasks. Your choices remain recorded when you close this page.', empty: 'No decisions recorded yet.', loading: 'Loading decisions…', refresh: 'Refresh decisions', more: 'Load more decisions',
  monitorFailure: 'Could not refresh decisions. Refresh before deciding; displayed data may be outdated.', uncertain: 'The decision may have been recorded. Check the refreshed state before repeating. Decisions are never resent automatically.',
  pending: 'Waiting for your decision', approved: 'Consent recorded', denied: 'Decision recorded · generation not allowed', revoked: 'Consent revoked', consumed: 'Consent used at the start of the call', stale: 'This request no longer matches the current state. Refresh the task and decisions.', expired: 'This request expired. Resume the task to request a new decision.',
  task: 'Task', objective: 'Objective', expectedResult: 'Expected result', reviewTask: 'Review objective and expected result', model: 'Model', destination: 'Destination', environment: 'Environment', identity: 'Identity', action: 'Action', control_plane: 'Bees service', bees_user: 'Your Bees access', generate: 'Generate a text response', scope: 'Rule scope', exactScope: 'Only this bee, action, destination, model, environment and identity. The rule also applies to future requests in this scope.', onceScope: 'Only this prepared call. Changes to instructions, context, model, rules or destination invalidate consent.', expiration: 'Request valid until {{time}}', cost: 'The task content and context are sent to the indicated destination. The call may consume provider credits.',
  allow_once: 'Allow once', allow_rule: 'Save a rule for this scope', ask: 'Always ask', deny: 'Block this scope', help_allow_once: 'Authorizes this call once and queues the task. Skips asking only for this call; blocks still take precedence. Does not create a permanent rule.', help_allow_rule: 'Saves permission for the displayed scope and queues the task. Applicable blocks still take precedence.', help_ask: 'Saves an ask rule for this scope. Does not allow or resume the task.', help_deny: 'Saves a block for this scope. The task stays stopped.',
  confirm: 'Confirm decision', saving: 'Recording…', back: 'Back', reason: 'Reason (optional)', decisionSaved: 'Decision recorded. The service reevaluates rules before the call.', revoke: 'Revoke consent', revokeImpact: 'Revokes only unused one-time consent. An already started call is not undone. Permanent rules are edited in Autonomy.', confirmRevoke: 'Confirm revocation', revokedSaved: 'Consent revoked.', editPolicies: 'Edit rules in conversation', policiesHelp: 'Type /autonomia or use the button to open the rule editor. Model text never changes permissions.', closePolicies: 'Close rule editor', reviewFirst: 'Choose the scope and confirm below.', lastDecision: 'Last decision', stillWaiting: 'the task is still waiting',
}
const es: Translations = {
  title: 'Decisiones de la abeja', description: 'Estas solicitudes pertenecen a las tareas indicadas. Tus decisiones quedan registradas al cerrar esta página.', empty: 'Todavía no hay decisiones registradas.', loading: 'Cargando decisiones…', refresh: 'Actualizar decisiones', more: 'Cargar más decisiones', monitorFailure: 'No se pudieron actualizar las decisiones. Actualiza antes de decidir; los datos pueden estar desactualizados.', uncertain: 'La decisión puede haberse registrado. Comprueba el estado actualizado antes de repetir. Ninguna decisión se reenvía automáticamente.',
  pending: 'Esperando tu decisión', approved: 'Consentimiento registrado', denied: 'Decisión registrada · generación no permitida', revoked: 'Consentimiento revocado', consumed: 'Consentimiento utilizado al iniciar la llamada', stale: 'Esta solicitud ya no corresponde al estado actual. Actualiza la tarea y las decisiones.', expired: 'Esta solicitud venció. Retoma la tarea para solicitar una nueva decisión.', task: 'Tarea', objective: 'Objetivo', expectedResult: 'Resultado esperado', reviewTask: 'Revisar objetivo y resultado esperado', model: 'Modelo', destination: 'Destino', environment: 'Entorno', identity: 'Identidad', action: 'Acción', control_plane: 'Servicio Bees', bees_user: 'Tu acceso en Bees', generate: 'Generar una respuesta de texto', scope: 'Alcance de la regla', exactScope: 'Solo esta abeja, acción, destino, modelo, entorno e identidad. La regla también se aplica a solicitudes futuras en este alcance.', onceScope: 'Solo esta llamada preparada. Cambiar instrucciones, contexto, modelo, reglas o destino invalida el consentimiento.', expiration: 'Solicitud válida hasta {{time}}', cost: 'El contenido y contexto de la tarea se enviarán al destino indicado. La llamada puede consumir créditos del proveedor.',
  allow_once: 'Permitir una vez', allow_rule: 'Guardar regla en este alcance', ask: 'Siempre preguntar', deny: 'Bloquear este alcance', help_allow_once: 'Autoriza esta llamada una vez y pone la tarea en cola. Omite la pregunta solo para esta llamada; los bloqueos siguen prevaleciendo. No crea una regla permanente.', help_allow_rule: 'Guarda permiso para el alcance mostrado y pone la tarea en cola. Los bloqueos aplicables siguen prevaleciendo.', help_ask: 'Guarda una regla para preguntar en este alcance. No permite ni retoma la tarefa.', help_deny: 'Guarda un bloqueo en este alcance. La tarea sigue detenida.', confirm: 'Confirmar decisión', saving: 'Registrando…', back: 'Volver', reason: 'Motivo (opcional)', decisionSaved: 'Decisión registrada. El servicio revisa las reglas antes de la llamada.', revoke: 'Revocar consentimiento', revokeImpact: 'Revoca solo el consentimiento puntual sin usar. No deshace una llamada iniciada. Las reglas permanentes se editan en Autonomía.', confirmRevoke: 'Confirmar revocación', revokedSaved: 'Consentimiento revocado.', editPolicies: 'Editar reglas en la conversación', policiesHelp: 'Escribe /autonomia o usa el botón para abrir el editor de reglas. El texto del modelo no modifica permisos.', closePolicies: 'Cerrar editor de reglas', reviewFirst: 'Elige el alcance y confirma abajo.', lastDecision: 'Última decisión', stillWaiting: 'la tarea sigue esperando',
}
export const approvalResources = { 'pt-BR': pt, en, es }
