const pt = {
  navigation: 'Autonomia', title: 'O que sua abelha pode fazer', description: 'Defina regras para gerar respostas na conversa e nas tarefas. Computadores e outras ferramentas chegam nas próximas etapas.',
  defaults: 'Sem uma regra aplicável, gerar respostas é permitido. Bloquear sempre prevalece. Perguntar suspende a geração; uma aprovação humana pode dispensar perguntas específicas somente no escopo confirmado.',
  approvalOrigin: 'Salva por uma decisão humana: dispensa as perguntas confirmadas neste escopo. Bloqueios continuam prevalecendo; regras novas ou alteradas podem exigir outra decisão.',
  approvalEditImpact: 'Salvar qualquer alteração transforma esta regra em uma regra manual e remove sua exceção às perguntas confirmadas. Outras regras de perguntar poderão voltar a interromper a geração.',
  changes: 'Alterações valem antes da próxima chamada. Elas não desfazem uma chamada já enviada. Após liberar uma regra, retome a tarefa manualmente.',
  askHelp: 'Em tarefas, perguntar cria um cartão de decisão na conversa. No chat direto, a geração aguarda revisão da regra. Alterar esta regra não retoma uma tarefa automaticamente.',
  newRule: 'Nova regra', editRule: 'Editar regra', revokeRule: 'Revogar regra', save: 'Salvar regra', saving: 'Salvando…', cancel: 'Cancelar', name: 'Nome da regra', optional: 'opcional', reason: 'Motivo ou contexto',
  effect: 'Decisão', allow: 'Permitir', ask: 'Perguntar antes', deny: 'Bloquear', scope: 'Aplicar a', allGeneration: 'Todas as respostas desta abelha', currentConnection: 'Conexão e modelo atuais', savedConnection: 'Conexão e modelo desta regra', connection: 'Conexão', model: 'Modelo',
  empty: 'Nenhuma regra cadastrada.', emptyHelp: 'Sua abelha pode gerar respostas com o modelo escolhido. Cadastre uma regra para restringir esse uso.',
  saved: 'Regra salva.', revoked: 'Regra revogada. Outras regras continuam valendo.', active: 'Ativa', revokedStatus: 'Revogada', global: 'Regra geral · somente leitura', unsupported: 'Escopo avançado ou incompatível · você pode revogar esta regra', more: 'Existem mais regras no serviço. Use Carregar mais regras para consultá-las.',
  refresh: 'Atualizar regras', loading: 'Carregando regras…', stale: 'A lista abaixo é a última versão carregada. Atualize antes de fazer alterações.', conflict: 'A regra mudou em outra sessão. Seu formulário foi preservado; recarregue a versão atual antes de salvar.', reload: 'Recarregar versão atual', reloaded: 'Versão atual recarregada. Revise a decisão e o escopo antes de salvar.',
  revokeConfirm: 'Revogar esta regra?', revokeImpact: 'Revogar remove esta restrição ou autorização das próximas chamadas. Sem outra restrição aplicável, gerar respostas volta a ser permitido.', confirmRevoke: 'Confirmar revogação', noModel: 'Configure um modelo para criar uma regra limitada à conexão atual.', defaultName: 'Geração de respostas',
  savedScope: 'Escopo atual da regra', revokeConflict: 'A regra mudou antes da revogação. A lista foi atualizada; revise a regra antes de tentar novamente.',
  loadMore: 'Carregar mais regras', retryPage: 'Tentar carregar esta página novamente',
}
const en: Record<keyof typeof pt, string> = {
  navigation: 'Autonomy', title: 'What your bee can do', description: 'Set rules for generating replies in conversations and tasks. Computers and other tools will arrive in future stages.',
  defaults: 'Without an applicable rule, generation is allowed. Deny always takes precedence. Ask suspends generation; human approval can skip specific questions only within the confirmed scope.',
  approvalOrigin: 'Saved through a human decision: skips the confirmed questions within this scope. Blocks still take precedence; new or changed rules may require another decision.',
  approvalEditImpact: 'Saving any edit turns this into a manual rule and removes its exception to the confirmed questions. Other ask rules may interrupt generation again.',
  changes: 'Changes apply before the next call. They do not undo a call already sent. After allowing a rule, resume the task manually.', askHelp: 'For tasks, ask creates a decision card in the conversation. For direct chat, generation waits for rule review. Editing this rule does not automatically resume a task.',
  newRule: 'New rule', editRule: 'Edit rule', revokeRule: 'Revoke rule', save: 'Save rule', saving: 'Saving…', cancel: 'Cancel', name: 'Rule name', optional: 'optional', reason: 'Reason or context', effect: 'Decision', allow: 'Allow', ask: 'Ask first', deny: 'Deny', scope: 'Apply to', allGeneration: 'All replies by this bee', currentConnection: 'Current connection and model', savedConnection: 'This rule’s connection and model', connection: 'Connection', model: 'Model',
  empty: 'No rules registered.', emptyHelp: 'Your bee can generate replies with the selected model. Add a rule to restrict this use.', saved: 'Rule saved.', revoked: 'Rule revoked. Other rules still apply.', active: 'Active', revokedStatus: 'Revoked', global: 'General rule · read only', unsupported: 'Advanced or incompatible scope · you can revoke this rule', more: 'The service contains more rules. Choose Load more rules to view them.', refresh: 'Refresh rules', loading: 'Loading rules…', stale: 'The list below is the last loaded version. Refresh before making changes.', conflict: 'The rule changed in another session. Your form is preserved; reload the current version before saving.', reload: 'Reload current version', reloaded: 'Current version loaded. Review the decision and scope before saving.', revokeConfirm: 'Revoke this rule?', revokeImpact: 'Revoking removes this restriction or permission from future calls. Without another applicable restriction, generating replies becomes allowed again.', confirmRevoke: 'Confirm revocation', noModel: 'Configure a model to create a rule limited to the current connection.', defaultName: 'Reply generation',
  savedScope: 'Current rule scope', revokeConflict: 'The rule changed before revocation. The list was refreshed; review the rule before trying again.',
  loadMore: 'Load more rules', retryPage: 'Retry loading this page',
}
const es: Record<keyof typeof pt, string> = {
  navigation: 'Autonomía', title: 'Qué puede hacer tu abeja', description: 'Define reglas para generar respuestas en conversaciones y tareas. Los ordenadores y otras herramientas llegarán en las próximas etapas.',
  defaults: 'Sin una regla aplicable, se permite generar. Bloquear siempre prevalece. Preguntar suspende la generación; una aprobación humana puede omitir preguntas específicas solo en el alcance confirmado.', changes: 'Los cambios se aplican antes de la siguiente llamada. No deshacen una llamada ya enviada. Tras permitir una regla, reanuda la tarea manualmente.', askHelp: 'En tareas, preguntar crea una tarjeta de decisión en la conversación. En chat directo, la generación espera revisión de la regla. Editar esta regla no retoma una tarea automáticamente.',
  approvalOrigin: 'Guardada mediante una decisión humana: omite las preguntas confirmadas en este alcance. Los bloqueos siguen prevaleciendo; reglas nuevas o modificadas pueden exigir otra decisión.',
  approvalEditImpact: 'Guardar cualquier cambio la convierte en una regla manual y elimina la excepción a las preguntas confirmadas. Otras reglas de preguntar pueden detener la generación otra vez.',
  newRule: 'Nueva regla', editRule: 'Editar regla', revokeRule: 'Revocar regla', save: 'Guardar regla', saving: 'Guardando…', cancel: 'Cancelar', name: 'Nombre de la regla', optional: 'opcional', reason: 'Motivo o contexto', effect: 'Decisión', allow: 'Permitir', ask: 'Preguntar antes', deny: 'Bloquear', scope: 'Aplicar a', allGeneration: 'Todas las respuestas de esta abeja', currentConnection: 'Conexión y modelo actuales', savedConnection: 'Conexión y modelo de esta regla', connection: 'Conexión', model: 'Modelo',
  empty: 'No hay reglas registradas.', emptyHelp: 'Tu abeja puede generar respuestas con el modelo elegido. Añade una regla para restringir este uso.', saved: 'Regla guardada.', revoked: 'Regla revocada. Las otras reglas siguen vigentes.', active: 'Activa', revokedStatus: 'Revocada', global: 'Regla general · solo lectura', unsupported: 'Ámbito avanzado o incompatible · puedes revocar esta regla', more: 'Hay más reglas en el servicio. Elige Cargar más reglas para consultarlas.', refresh: 'Actualizar reglas', loading: 'Cargando reglas…', stale: 'La lista es la última versión cargada. Actualízala antes de hacer cambios.', conflict: 'La regla cambió en otra sesión. Se conservó tu formulario; carga la versión actual antes de guardar.', reload: 'Cargar versión actual', reloaded: 'Versión actual cargada. Revisa la decisión y el ámbito antes de guardar.', revokeConfirm: '¿Revocar esta regla?', revokeImpact: 'Revocar elimina esta restricción o permiso de las próximas llamadas. Sin otra restricción aplicable, se vuelve a permitir generar respuestas.', confirmRevoke: 'Confirmar revocación', noModel: 'Configura un modelo para crear una regla limitada a la conexión actual.', defaultName: 'Generación de respuestas',
  savedScope: 'Ámbito actual de la regla', revokeConflict: 'La regla cambió antes de revocarla. Se actualizó la lista; revisa la regla antes de reintentar.',
  loadMore: 'Cargar más reglas', retryPage: 'Reintentar cargar esta página',
}
export const policyResources = { 'pt-BR': pt, en, es }
